version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nodepm2cicd1
permissions:
  - object: /home/ec2-user/nodepm2cicd1
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user
