version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Build step (optional, skipping in this case)"
  post_build:
    commands:
      - echo "Zipping artifacts..."
      - zip -r deploy.zip *  
artifacts:
  files:
    - deploy.zip
  discard-paths: yes